config/routes.rb
Rainforest2::Application.routes.draw do
  
  resources :products do
    resources :reviews, except: [:index, :show]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products
  has_many :reviews

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      redirect_to new_session_path, :alert => "Please log in first!"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:edit, :new]
  before_filter :load_product, :except => [:index, :new, :create]

  def index
    @products = if params[:search]
      Product.where("name ILIKE ?", "%#{params[:search]}%")
    else 
      Product.order("id")
    end

    if request.xhr?
      render partial: "product", collection: @products
    end

  end

  def show
    @review = @product.reviews.new
  end

  def edit
  end

  def update
    if current_user.id == @product.user_id
      if @product.update_attributes(product_params)
        redirect_to product_path(@product)
      else
        render :edit
      end
    else
      redirect_to product_path(@product), :alert => "You do not have permission to update this item."
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    if current_user.id == @product.user_id
      @product.destroy
      redirect_to products_path
    else
      redirect_to product_path(@product), :alert => "You do not have permission to delete this item."
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

  def load_product
    @product = Product.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.user_id = current_user.id
    
    if @review.save
      redirect_to product_path(@product), :notice => "Review added!"
    else
      redirect_to product_path(@product), :alert => "Review not added"
    end
  end


  private

  def review_params
    params.require(:review).permit(:comment, :product_id, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by("username = ?", params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path, :notice => "Logged in!"
    else
      flash[:alert] = "Invalid login details. Please try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_path, :notice => "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_path, :notice => "Signed up!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  DEBUGGING = false
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% elsif flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>

<div class="user_panel">
  <ul>
    <% if current_user %>
      <li>Logged in as <%= current_user.username %></li>
      <li><%= link_to "Log Out", session_path(current_user.id), :method => :delete %></li>
    <% else %>
      <li><%= link_to "Log In", new_session_path %></li>
      <li><%= link_to "Register", new_user_path %></li>
    <% end %>
    <li>
        <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
    </li>
  </ul>
</div>

<%= yield %>

</body>
</html>

app/views/products/_product.html.erb
<li>
  <h3><%= link_to product.name, product_path(product.id) %></h3>
  <p><%= product.description %></p>
  <h4><%= product.price %></h4>
</li>

app/views/products/_product_form.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br><br>

  <%= f.label :price %><br>
  <%= f.text_field :price %><br><br>


  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>
<br>

<%= render "product_form" %>

<p><%= link_to "< Cancel", product_path(@product) %>

app/views/products/index.html.erb
<h1>Viewing All Products</h1>
<ul id="products">
  <%= render @products %>
    
</ul>

<p><%= link_to "Add New Product", new_product_path %></p>

app/views/products/new.html.erb
<h1>Add New Product</h1>
<p>Enter product details below:</p>
<%= render "product_form" %>

<p><%= link_to "< Cancel", products_path %></p>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.description %></p>
<p><%= @product.price %></p>
<% if current_user && session[:user_id] == @product.user_id %>
<p><%= link_to "Edit this product", edit_product_path(@product) %> | <%= link_to "Delete this product", product_path(@product), method: :delete %></p>
<% end %>
<br><br>
<p><%= link_to "< Back to Products", products_path %></p>

<h2>Reviews</h2>
<% @product.reviews.each do |rev| %>
  <p><%= rev.comment %></p>
  <p style="font-size: 0.75em"></p>

<% end %>

<h3>Add a Review</h3>
<%= form_for ([@product, @review]) do |f| %>
  <%= f.text_field :comment %> <%= f.submit "Publish" %>
<% end %>

<%= debug @product if ApplicationHelper::DEBUGGING %>

app/views/users/new.html.erb
<h1>Register Account</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br><br>

  <%= f.submit %>


<% end %>